project:
  type: default

course:
  canvas_url: "https://colostate.instructure.com/courses/218386"
  site_url: "https://jbayham.github.io/arec-330/"
  
# format:
  # pdf:
  #   toc: false
  #   number-sections: true
  #   documentclass: article
  #   geometry: margin=1in