# Site settings
title: AREC 330
subtitle: Data Driven Decision Making in Agricultural and Resource Economics
description: |
  Welcome to the course webpage for AREC 330 -- Data-Driven Decision Making in Agricultural and Resource Economics!

baseurl: "/arec-330" # the subpath of your site, e.g. /blog/
url: "https://jbayham.github.io" # the base hostname & protocol for your site
syllabus: "/syllabus"
githubdir: "jbayham/arec-330"

# Author/user information
email: jbayham@colostate.edu
#twitter_username: stevenvmiller
github_username:  jbayham
# authorurl: "https://sites.google.com/site/judebayham/home"
# address: |
#     Department of Political Science
#     232 Brackett Hall
#     Clemson, SC 29634-1354


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
